# Generated by Django 5.0.4 on 2024-04-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.IntegerField(max_length=200)),
                ('Married', models.IntegerField(max_length=200)),
                ('Dependents', models.IntegerField(max_length=200)),
                ('Education', models.IntegerField(max_length=200)),
                ('Self_Employed', models.IntegerField()),
                ('ApplicantIncome', models.IntegerField()),
                ('CoapplicantIncome', models.IntegerField()),
                ('LoanAmount', models.IntegerField()),
                ('Loan_Amount_Term', models.IntegerField()),
                ('Credit_History', models.IntegerField()),
                ('Property_Area', models.IntegerField(max_length=7)),
            ],
        ),
    ]
